package com.example;
/*
 * 예외 처리 Exception handling 
 * 
 * 
 */
public class TryCatchExample {

	
	public static void main(String[] args) {
		
		System.out.println("Start...");
		
		try {
			Thread.sleep(5000);
		} catch (Exception e) {
			
		}
		
		System.out.println("End... ");
	}
	
	public static void main3(String[] args) {
		// 다중 catch로 예외 처리
		
		int x = 3;
		String str = "Hello";
		
		try {
			int result = 10/x;	// ArithmeticException		
			
			str.charAt(0);		// NullPointerException
			
			int[] nums = {1, 2, 3};
			nums[3] = 10;
			
		} catch (ArithmeticException e) {
			System.out.println("0으로 나눌 수 없습니다.");
//			e.printStackTrace();	// error print 
		} catch (NullPointerException e) {
			System.out.println("Null 입니다. Null은 연산할 수 없습니다.");
//		} catch (Exception e) {
//			System.out.println(e.getMessage());
		} finally {
			System.out.println("finally block's always working.");
		}
		
		System.out.println("End.. ");
		
	}
	
	
	public static void main2(String[] args) {
		// try-catch 예외 처리 
		
		System.out.println("start");
		System.err.println("start");		// err type print
		System.out.println("start");
		
		try {
			int result = 10/0;		// runtime exception을 조상으로 둔 예외클래스. 
		} catch (ArithmeticException e) {
			
		}
		
		
		
		
		System.out.println("End.. ");
		
	}

}
